### ISSUE TITLE
Update Organizations and Schools 

### ISSUE THREAD

**Issue by why-science** [why-science/demo#1]
There should be only one organization. Not the organizations from STEAM XPRESS on demo.whyscience.com

Organization: Demo Organization  (Rename organization "Subscription" with "Demo Organization"

School: Demo School (Rename school "STEAM XPRESS School" with "Demo School")

**Comment by rajthilak87** [comment]
Completed

SuperAdmin
itadmin@whyscience.com
marai312!

Demo School admin 
User ID : test.teacher1@whyceeyes.com
Pass      : 30de402d

Demo Coach 
User id : test.teacher2@whyceeyes.com
Pass     : 33f6452e

Demo Instructor 
User id : test.teacher4@whyceeyes.com
Pass     : 67d603e3

**Comment by why-science** [comment]
Thanks
