### ISSUE TITLE
Update Configure Menu under itadmin@whyscience.

### ISSUE THREAD

**Issue by why-science** [why-science/demo#10]
Remove the following menus under  Configure
1. About Us
2. Sitemap
3. Request Account
4. Login page footer box 1
5. Login page footer box 2
6. Thanks for visiting us!
7. Help
8. Request Account Form
9. Rules 
![image](https://user-images.githubusercontent.com/70287522/173410617-b95eacf0-6929-48fa-a239-216df72cc8af.png)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
