### ISSUE TITLE
Remove itadmin@steamxpress.us from systems emails 

### ISSUE THREAD

**Issue by why-science** [why-science/demo#11]
Remove itadmin@steamxpress.us from the emails below. System emails should be sent from itadmin@whyscience.com ONLY

![image](https://user-images.githubusercontent.com/70287522/173436320-ead3684e-086c-4456-bc42-163f3481ce29.png)

**Comment by why-science** [comment]
Edit Instructor Welcome Email as shown below
Replace "WhyScience Learning Center" with "Latter Rain Platform" in 1 & 2
Replace text in #3 with "Welcome! We are humbled that you are joining our community."
Check URL.
Remove all text that has been crossed out.
Replace "Regards" in 4 with "Yours in Christ"
Check Why Science Logo. Logo not displaying correctly.
![image](https://user-images.githubusercontent.com/70287522/173439011-14bdc459-26e5-4001-99c8-1c6172fb0e29.png)
![image](https://user-images.githubusercontent.com/70287522/173439915-5398008c-51b8-4cc1-b5c6-bcb5e522dd28.png)

**Comment by rajthilak87** [comment]
Fixed

Replace text with "Welcome! We are humbled that you are joining our community."  ---> Not Fixed
Note: Replace "Regards" in 4 with "Yours in Christ" ---> Not fixed

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks

**Comment by rajthilak87** [comment]
item 2 cannot be changed because the name(WhyScience Learning Cente) would be synced with the email(itadmin@whyscience.com) created.

**Comment by rajthilak87** [comment]
In the mail content

On click "here" takes the user to the WBF pdf, it should be removed right ? 

![image](https://user-images.githubusercontent.com/89064511/173831087-d6325463-b98d-41a3-af9f-633839c29287.png)


![image](https://user-images.githubusercontent.com/89064511/173831565-a37d2c1e-dbda-4e36-83cc-0ec99d064e13.png)
