### ISSUE TITLE
Branding - Change WhyScience Learning Center to Latter Rain Platform

### ISSUE THREAD

**Issue by why-science** [why-science/demo#12]
Change WhyScience Learning Center to "Latter Rain Platform"
![image](https://user-images.githubusercontent.com/70287522/173597665-7312928f-e653-4c98-b52c-22a7ca577e9c.png)

**Comment by why-science** [comment]
Please update status

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
