### ISSUE TITLE
No right arrow displayed for STEP 1 even though there is no Summative Assessment

### ISSUE THREAD

**Issue by why-science** [why-science/demo#15]
![image](https://user-images.githubusercontent.com/70287522/173661153-38505868-1e4e-49f2-886c-dcd07700859d.png)

**Comment by rajthilak87** [comment]
FIXED

![image](https://user-images.githubusercontent.com/89064511/173841492-c64f0dc3-610c-4815-a1e8-01696786c72e.png)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
