### ISSUE TITLE
Remove all STEAM XPRESS documents in  demo.whyscience.com Gallery

### ISSUE THREAD

**Issue by why-science** [why-science/demo#2]
Remove all files from Gallery
![image](https://user-images.githubusercontent.com/70287522/158304017-f3d03334-1a3d-4569-a778-112ded381435.png)

**Comment by rajthilak87** [comment]
Completed

![image](https://user-images.githubusercontent.com/89064511/158395136-3fc39ce5-a4f4-4681-952e-779ccea333b1.png)

**Comment by why-science** [comment]
Thank you
