### ISSUE TITLE
Update colors for module steps 

### ISSUE THREAD

**Issue by why-science** [why-science/demo#22]
Use the colors already on the system

1. Steps 1 - 8  (Red)

2. Steps 9 - 16 (Purple/Violet)

3. Steps 17 - 24 (Green)

4. Step 25: Blue

Remove labels Week 1, Week 2, Week 3, Week 4
![image](https://user-images.githubusercontent.com/70287522/173929614-9918c836-0362-452b-84b5-824da1ca7e0e.png)

**Comment by rajthilak87** [comment]
Fixed 

Should we implement the same changes in the module view?

**Comment by why-science** [comment]
Yes. Throughout the system. Thanks

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
![image](https://user-images.githubusercontent.com/70287522/174704147-4fe68425-1274-4418-aead-f99d1087c1da.png)

**Comment by why-science** [comment]
Thanks
