### ISSUE TITLE
Module available for organization - Archdiocese of Hartford - Restoring Holiness Only

### ISSUE THREAD

**Issue by why-science** [why-science/demo#23]
Only the "Restoring Holiness" module should be available for Coaches in the Archdiocese of Hartford to assign to instructors.

Make sure only active modules, not modules in the Module Trashbox are shown. I emptied the module trashbox before taking this screenshot.

![image](https://user-images.githubusercontent.com/70287522/173927103-3a5402ae-9834-4ab9-8cb6-0a5c8c748ac2.png)

**Comment by why-science** [comment]
On the front end the correct module is shown. On the backend all the modules available on the system are shown. 
When we add an organization should we assign modules to that organization? How do we resolve this issue? In the future, not all organizations will have access to all modules

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
