### ISSUE TITLE
Errors in Welcome Email when Coach adds single instructor with + sign

### ISSUE THREAD

**Issue by why-science** [why-science/demo#24]
![image](https://user-images.githubusercontent.com/70287522/173879874-6daef256-a206-4dfd-abfe-f9255b88c5c8.png)

**Comment by rajthilak87** [comment]
Fixed

![image](https://user-images.githubusercontent.com/89064511/173891330-ffb47074-ca8e-4d06-8443-dbb539826bda.png)

**Comment by why-science** [comment]
Thanks
