### ISSUE TITLE
Rubrics Grading tool not saving content - FIX

### ISSUE THREAD

**Issue by why-science** [why-science/demo#26]
Please populate the rubric for each week with the information below:

Mastery (3 points) for Week 1, Week 2, Week 3, and Week 4.

**In everything**:

- I am calm and can focus on the task at hand.
- I rely on God's wisdom to act.
- I am centered in God's presence.
- I accept difficult situations with peace and joy.'
- My manner of interacting with people and my environment is God-centered.

Proficient (2 points) Week 1, Week 2, Week 3, Week 4

**Sometimes**:
- I am calm and can focus on the task at hand.
- I rely on God's wisdom to act.
- I am centered in God's presence.
- I accept difficult situations with peace and joy.'
- My manner of interacting with people and my environment is God-centered.

Needs Improvement (1 point) Week 1, Week 2, Week 3, Week 4

**Rarely or Never**:
- I am calm and can focus on the task at hand.
- I rely on God's wisdom to act.
- I am centered in God's presence.
- I accept difficult situations with peace and joy.'
- My manner of interacting with people and my environment is God-centered.

**Comment by why-science** [comment]
rename Week 1  "Survey 1"
rename Week 2  "Survey 2"
rename Week 3  "Survey 3"
rename Week 4  "Survey 4"

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Errors in the gradebook for instructors, coaches and admin have been introduced with this fix see issue #34
