### ISSUE TITLE
Change Allow Access Feature  - Step 3, Step 8, Step 11, Step 16, Step 19, Step 24 (Just like on training.whyscience.com)

### ISSUE THREAD

**Issue by why-science** [why-science/demo#28]
Replace Week 1, Week 2, Week 3 and Week 4 with 
Step 3, Step 8, Step 11, Step 16, Step 19, Step 24 just like in training.whyscience.com
![image](https://user-images.githubusercontent.com/70287522/173942514-d65304ec-858e-4cdf-9044-8aa4318e986d.png)

![image](https://user-images.githubusercontent.com/70287522/173942407-7a9e8173-6741-4d52-80b7-7a9ddd7c0e8a.png)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thank you
