### ISSUE TITLE
Display 20 characters for Class Name

### ISSUE THREAD

**Issue by why-science** [why-science/demo#29]
![image](https://user-images.githubusercontent.com/70287522/173941593-7372ecee-2925-439c-a181-983b435c8715.png)
![image](https://user-images.githubusercontent.com/70287522/173941677-9d6b74ec-9825-4904-867a-711d6300802d.png)
![image](https://user-images.githubusercontent.com/70287522/173941790-9a9a079f-907f-4080-9d54-80f197f464ad.png)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
