### ISSUE TITLE
For Coach: Change "Schools" to "Parish"; Change "Schools" to "Parishes"

### ISSUE THREAD

**Issue by why-science** [why-science/demo#30]
![image](https://user-images.githubusercontent.com/70287522/173946630-e6170115-4d63-4225-bb23-b24db678703a.png)
![image](https://user-images.githubusercontent.com/70287522/173947215-909b8db3-e3b4-4cf0-9a87-368b4d047eeb.png)
![image](https://user-images.githubusercontent.com/70287522/173948516-d296e639-5bc9-4c77-9d4d-ee7cfabf59c3.png)

**Comment by why-science** [comment]
Make this change for School Admin and ITAdmin.

Change "School Admin" to "Parish Admin"

**Comment by rajthilak87** [comment]
Is it applicable for the coach alone or we should replace it for the instructors/Parish Admin too? Throughout the system ?

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
It is not applicable to coach alone. Want this change throughout the system. Will create a new issue to address the issue for ITAdmin and School Admin.
