### ISSUE TITLE
Replace Getting Started Document in Welcome Email for Instructors with Attached Document

### ISSUE THREAD

**Issue by why-science** [why-science/demo#31]
Replace Welcome Email for Instructors with the document below:
[Getting_Started_Guide_for_Instructors_06_15_2022.pdf](https://github.com/why-science/demo/files/8915730/Getting_Started_Guide_for_Instructors_06_15_2022.pdf)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thank you
