### ISSUE TITLE
Replace Getting Started Guide for Coaches in Welcome Email with attached document

### ISSUE THREAD

**Issue by why-science** [why-science/demo#33]
Replace Getting Started Guide for Coaches in Welcome Email with attached document below:
[Getting_Started_Guide_for_Coaches_06_15_2022.pdf](https://github.com/why-science/demo/files/8915734/Getting_Started_Guide_for_Coaches_06_15_2022.pdf)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
