### ISSUE TITLE
Gradebook Errors

### ISSUE THREAD

**Issue by why-science** [why-science/demo#34]
Content of the gradebook not displaying correctly
Week 1  should be Survey 1
Week 2 should be Survey 2
Week 3 should be Survey 3
Week 4 should be Survey 4

When a week is selected only that Week should be listed on the right FIX
Enter and display buttons not working correctly
![image](https://user-images.githubusercontent.com/70287522/174389365-9b56f0ba-2792-4682-b283-3dce203faaf9.png)

Check for instructor, coach and admins as well

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
