### ISSUE TITLE
Change Titles for Rubrics in the Gradebook and Rubric Grading

### ISSUE THREAD

**Issue by why-science** [why-science/demo#41]
Change Mastery (3 points) to **Sufficient** (3 points)
Change Proficient (2 points) to **Developing** (2 points)
![image](https://user-images.githubusercontent.com/70287522/175142027-6e763083-136b-46d1-ba6c-056e1cfc018f.png)
![image](https://user-images.githubusercontent.com/70287522/175211000-b9fd71e2-bc54-4297-ac52-dd9d9859cd4b.png)

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thank you
