### ISSUE TITLE
Errors: Coach assigning modules to instructors

### ISSUE THREAD

**Issue by why-science** [why-science/demo#6]
I added akpaly@gmail.com as an instructor on the backend
![image](https://user-images.githubusercontent.com/70287522/170323503-84e61bfd-be9b-4118-a482-f91f92d1fa27.png)

However I do not see akpaly@gmail.com as an instructor on the front end or associated with the Prayer Warrior Module.
![image](https://user-images.githubusercontent.com/70287522/170323784-b7ec51d1-411e-457a-896c-9005d0398b37.png)
![image](https://user-images.githubusercontent.com/70287522/170323914-e1ea3c35-c8e8-409d-9707-ed9f8a52f091.png)'

When logged in as instructor akpaly@gmail.com there are no modules assigned

![image](https://user-images.githubusercontent.com/70287522/170324695-197ab177-9b5a-4fb8-a607-df43c752c898.png)

Please fix this issue. Thanks.

**Comment by rajthilak87** [comment]
Issue Fixed

**Comment by why-science** [comment]
Thanks
