### ISSUE TITLE
Gallery does not display all uploaded files - Fix

### ISSUE THREAD

**Issue by why-science** [why-science/demo#7]
There are supposed to be two files. I only see one file - FIX
![image](https://user-images.githubusercontent.com/70287522/170404488-eda414d7-daba-4545-a7f2-4c23192a2b87.png)

**Comment by why-science** [comment]
When I upload files I see them.
![image](https://user-images.githubusercontent.com/70287522/170526189-cad2517a-d0da-4a83-9a6d-20d955176fab.png)


When I logout or leave the screen and open the gallery again, I do not see the files
![image](https://user-images.githubusercontent.com/70287522/170526488-2fa8cb3a-117b-4886-b07d-26644e4cb6ec.png)

**Comment by why-science** [comment]
Missing image icons for files in gallery - FIX

**Comment by rajthilak87** [comment]
Issue fixed

**Comment by why-science** [comment]
Thanks
