### ISSUE TITLE
Error uploading image to slider - FIX

### ISSUE THREAD

**Issue by why-science** [why-science/demo#8]
![image](https://user-images.githubusercontent.com/70287522/173280384-ac56c4b6-74ef-4a32-9b81-a813521d6781.png)

Here is the file I tried to upload
![former_rains_image jpg](https://user-images.githubusercontent.com/70287522/173280406-4cf88d2b-ee26-4f67-9e6f-d221e6caba0d.jpg)

The source for this file is https://www.chaimbentorah.com/2018/09/word-study-former-rains/

**Comment by rajthilak87** [comment]
Given image has been uploaded in the slider.

**Comment by why-science** [comment]
Thanks
