### ISSUE TITLE
Organization and School Changes

### ISSUE THREAD

**Issue by why-science** [why-science/demo#9]
Contact info for  Organization "St. Mary Parish" is 

5 Hillhouse Ave 
New Haven, CT 06511 
(203) 562-6193 

**Schools for St Mary Parish**
1. St Mary Parish New Haven   [Address: 5 Hillhouse Ave New Haven CT 06511]
2. St. Stanislaus Parish New Haven  [Address: 9 Eld St, New Haven, CT 06511]

**Comment by rajthilak87** [comment]
We have created the following schools under St Mary Parish

1) St Mary Parish New Haven [Address: 5 Hillhouse Ave New Haven CT 06511]
2) St. Stanislaus Parish New Haven [Address: 9 Eld St, New Haven, CT 06511]

**Comment by rajthilak87** [comment]
Issue Fixed. Updated the address Information.

**Comment by why-science** [comment]
Sorry please change Organization "St Mary Parish" to "Archdiocese of Hartford"

Address for Archdiocese of Hartford:
134 Farmington Ave
Hartford, CT 06105
860-541-6491
860-541-6309 fax

Website: https://archdioceseofhartford.org/

**Comment by why-science** [comment]
Remove School "Prayer Warriors"

**Comment by rajthilak87** [comment]
If we remove the school "Prayer warriors"  then the respective instructor will be removed

**Comment by why-science** [comment]
Yes remove the school Prayer Warriors

**Comment by why-science** [comment]
Please update status

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
